### ISSUE TITLE
Bypassing company-minimum-prefix-length

### ISSUE THREAD

**Issue by cpitclaudel** [vspinu/company-math#10]
Hey @vspinu,

company-math is an almost perfect replacement for TeX-related input methods, but I'm still missing one thing: there's a few symbols that are shorter than the default `three-characters` prefix that company-mode requires, and inserting these in rather unpleasant.

This issue can be fixed by either:
- Bypassing company-minimum-prefix-length by returning `(cons prefix t)` instead of the prefix itself.
- Including `\` in the prefix, so that two-symbols characters reach the default minimum prefix length.

I use the first solution in company-coq (I have a wrapper around company-math), and it works very nicely; the second one might be considered less intrusive, however.

**Comment by cpitclaudel** [comment]
A third option would be to bypass company's check and use the user-specified prefix length -1.

**Comment by cpitclaudel** [comment]
Happy to prepare a patch for any of these solutions.

**Comment by vspinu** [comment]
> Including \ in the prefix, so that two-symbols characters reach the default minimum prefix length.

I just did that for the sub(super)script patch. It starts now after one symbol character. 

Thanks for all the input and suggestions and sorry again for taking so long on these issues.

**Comment by cpitclaudel** [comment]
Thanks! I had implemented the (cons prefix t) solution myself in company-coq: https://github.com/cpitclaudel/company-coq/blob/master/company-coq.el#L3056
