### ISSUE TITLE
Setup with org-mode/markdown-mode

### ISSUE THREAD

**Issue by Kaligule** [vspinu/company-math#14]
company-math is supper usefull in latex-mode. I couldn't get it running in org-mode or markdown-mode, even if they use the exact same syntax for formulars. This might be because I lack a deeper understanding of how company and its backends work.

Is there a setup for org-mode and markdown-mode that works? And if so, could we add it to the README, since this might be relevant for others, too?

**Comment by vspinu** [comment]
What do you want to use, unicode? Then it is in the readme:

```
;; global activation of the unicode symbol completion 
(add-to-list 'company-backends 'company-math-symbols-unicode)
```

You should check the value of `company-backends` in org-mode and markdown mode. It could be that something which responds on `\` takes precedence  over `company-math-symbols-unicode`. In both modes the above setup works for me.

**Comment by Kaligule** [comment]
I am using `company-math-symbols-latex` (which is more usefull to me). Odly enough, your suggested setup works (in markdown-mode and org-mode) for the unicode-backend, but if I replace `unicode` with `latex` I don't get suggestions anymore.

The calue of `company-backends` is a list, `company-math-symbols-latex` being the first item. I am not sure what goes wrong here. Could you doublecheck if you get the same behaviour, please?

**Comment by vspinu** [comment]
I see. `company-math-symbols-latex` is not triggered in strings or comments. It is also honoring `company-math-allow-latex-symbols-in-faces` and `company-math-disallow-latex-symbols-in-faces`. You should customize the former one to `t` to allow latex symbols everywhere.

**Comment by Kaligule** [comment]
Wonderfull, thank you very much. This was precisely it. And of course, now that I know about it I see it clearly hinted at in the Readme. Sigh... I am sorry.

What was the reason to set the value of `company-math-allow-unicode-symbols-in-faces` to `t`, but  `company-math-allow-latex-symbols-in-faces` to `'(tex-math font-latex-math-face)`?

I  suggest to include the face `org-latex-and-related` in the default value of `math-allow-latex-symbols-in-faces`, so company-maths-latex and can work by default on orgmode formulars. It seems to me that markdown-mode doesn't have a special face for formulars or similar, so we can't do anything there.

**Comment by vspinu** [comment]
> What was the reason to set the value of company-math-allow-unicode-symbols-in-faces to t, but company-math-allow-latex-symbols-in-faces to '(tex-math font-latex-math-face)?

Unicode is useful pretty much everywhere as it inserts actual characters. Latex math symbols only in math environments, otherwise it doesn't compile ;) 

>  suggest to include the face org-latex-and-related

Good idea. I am not a frequent org user so I was not aware of it. What are those `related` things? Can we mess up with something inadvertently there?

**Comment by Kaligule** [comment]
The documentation says:

> Face used to highlight LaTeX data, entities and sub/superscript.

It sounds like this should be alright. I will do a pull request.

**Comment by whyfarer** [comment]
I just want to chime-in that reading through this issue has helped me to get my org-mode with latex setup running much mroe smoothly. I'm now using org-mode  + cdlatex + company-math which allows me to write latex in org-mode without too much pain. For anyone else who stumbles down this path, here's my `use-package` setup:

```;; also use company math to help with faster insertion
(use-package company-math
  :straight t
  :init
  (setq company-math-allow-latex-symbols-in-faces  t) ;; allow completion in org-mode text
  :config
  ;; local configuration for TeX modes
  (defun my-latex-mode-setup ()
    (setq-local company-backends
		(append '((company-math-symbols-latex company-latex-commands))
			company-backends)))

  (add-hook 'org-mode-hook 'my-latex-mode-setup))
```

ps: sorry for the necrobump, but the issue was still open...

**Comment by Kaligule** [comment]
I guess I forgot to close it back then. Thanks :)
