### ISSUE TITLE
Disallow (company-latex-commands) in latex math environments

### ISSUE THREAD

**Issue by duzaichuan** [vspinu/company-math#16]
When I register `company-math-symbols-latex` and `company-latex-commands` backends at the same time, the former becomes invalid in the math environment due to the latter.
<img width="186" alt="image" src="https://user-images.githubusercontent.com/32022901/51525672-1f5e1100-1e31-11e9-9959-92bff646e277.png">
<img width="169" alt="image" src="https://user-images.githubusercontent.com/32022901/51525595-f473bd00-1e30-11e9-91ba-c4e39926d6db.png">

Is it possible to disallow `company-latex-commands` in latex math environments?

**Comment by vspinu** [comment]
How do you register? The math should come before the latex one. How does your `company-backends` look in tex files? 

For the record I do see your first screenshot in math environments with the suggested configuration:

```el
(setq-local company-backends
                (append '((company-math-symbols-latex
						   company-latex-commands))
                        company-backends))
```

What is the company mode version you use?

**Comment by duzaichuan** [comment]
Sorry for being less informative. I use the latest version of company. When I tried with
```
(add-to-list 'company-backends 'company-math-symbols-latex)
(add-to-list 'company-backends 'company-latex-commands)
```
I ended up with only latex commands completion. Now I try the per-buffer setup, it works!
