### ISSUE TITLE
math symbols not available inside equations

### ISSUE THREAD

**Issue by casouri** [vspinu/company-math#17]
Currently, math symbols are not available inside math equations, such as:
```
\begin{equation}
...
\end{equation}
```

I try to look into the code,  but not sure about the purpose of `min-point` in `company-math--prefix`:

``` elisp
(defun company-math--prefix (regexp allow-faces disallow-faces)
  (let* ((face (get-text-property (point) 'face))
         (face (or (car-safe face) face))
         (insertp (and (not (memq face disallow-faces))
                       (or (eq t allow-faces)
                           (memq face allow-faces)))))
    (when insertp
      (save-excursion
        (let* ((ppss (syntax-ppss))
               (min-point (if (nth 3 ppss)
                              (max (nth 8 ppss) (point-at-bol))
                            (point-at-bol))))
          (when (looking-back regexp min-point 'greedy)
            (match-string 0)))))))
```

IIUC the fix is pretty easy to pull off: regexp match `\end{equation}` and `\begin{equation}`, if the nearest `begin` is after the nearest `end`, return prefix. That's just what I would do, of course.

**Comment by vspinu** [comment]
What do you mean by "not working"? What is your configuration?

 Do you see symbol completion but it inserts the name not the unicode character, but you want the unicode caracter? If so, then that's by design depending on your configuration. If you use only the unicode backend then check `company-math-disallow-unicode-symbols-in-faces`. If you use both unicode and latex then also check `company-math-allow-latex-symbols-in-faces`.

**Comment by casouri** [comment]
By "not available" I mean company doesn't complete math symbols.

Basically, the completions are only provided inside `$ ... $` and if I'm in
```
\begin{equation}
...
\end{equation}
```
there won't be any math symbol completion (as in `$ ... $`).

I suppose that math symbol completions are only enabled inside `$ ... $`, is that true?

**Comment by vspinu** [comment]
Math symbol completions (`company-math-symbols-latex` backend) is active in `company-math-allow-latex-symbols-in-faces` which is by default  `(tex-math font-latex-math-face org-latex-and-related)`.  For me the font inside `equation` environment is `font-latex-math-face`. What is for you?

**Comment by casouri** [comment]
You are right, inside `equation` environments there is no `tex-math` face while there is inside`$ ... $` (in my Emacs). That's probably because I'm not using auc-tex. I'll try to get the face working. Thanks 😄

**Comment by vspinu** [comment]
I see. If using auctex is not an option you can either set that variable to nil and activate those symbols everywhere, or implement your own font-lock keywords to set a face between the `\begin{equation}...\end{equation}` block. Or just write your own backend based on `company-math-symbols-latex`. Should be pretty straightforward.
