### ISSUE TITLE
LaTeX environment name can't be completed automatically. 

### ISSUE THREAD

**Issue by hongyi-zhao** [vspinu/company-math#20]
On Ubuntu 20.04, I'm using `AUCTeX` with `company-math` as the backends for unicode math symbols and latex tags. The corresponding configuration in my `~/.emacs.d/init.el` is shown as follows:
```emacs-lisp
(use-package company-math
  :config
  (add-to-list 'company-backends 'company-math-symbols-unicode)
  (defun my-latex-mode-setup ()
    (setq-local company-backends
                (append '((
                           company-math-symbols-latex
                           company-latex-commands
			  ))
                        company-backends)))
  (add-hook 'TeX-mode-hook 'my-latex-mode-setup))
```

With the above configuration, I find that the LaTeX environment name can't be completed automatically, as shown below:

![image](https://user-images.githubusercontent.com/11155854/126937207-eb643860-24aa-47d9-a443-4dbf942aa98c.png)

Any hints for this problem?

Regards,
HY

**Comment by vspinu** [comment]
company-math backends don't complete environment names. Only latex symbols and unicode characters. You are looking for latex-specific backend which is aware of the syntax of the latex code. 

What surprises me is that company math backends are triggered in that position. They should not be because they are reacting to prefix `\`. What did you do to generate this screenshot?

**Comment by hongyi-zhao** [comment]
> What surprises me is that company math backends are triggered in that position. They should not be because they are reacting to prefix `\`. What did you do to generate this screenshot?

I'm not so clear what's your meaning. Could you please tell me exactly what to do next?

**Comment by vspinu** [comment]
The prefix computation was too aggressive and was hijacking other backends. In your example the backend which should betriggered is `company-capf`, not company-math. Should be fixed now. Thanks for reporting.

**Comment by hongyi-zhao** [comment]
Thank you for your fix. It does the trick:

![image](https://user-images.githubusercontent.com/11155854/127756118-a6358509-f7c8-4fdc-a98b-ff137c4859df.png)
