### ISSUE TITLE
Documentation issue

### ISSUE THREAD

**Issue by LordZorgoth** [vspinu/company-math#3]
In the documentation, there is a hook that is supposed to set up company mode. It involves tex-mode-hook.

tex-mode-hook doesn't work on my computer, but TeX-mode-hook does.

The documentation should mention TeX-mode-hook as an option.

**Comment by vspinu** [comment]
`TeX-mode-hook` is part of auctex but not everyone is using auctex. `tex-mode-hook` is not defined by default but it's run by `tex-mode` if the user has added anything to that hook. So, you should be fine either way.
